# Site
name: "Blog for STAC"
title: "AstroThoughts"
description: "Blog of the Space Technology and Astronomy Cell"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  shreyas:
    name: Shreyas
    display_name: astroshreyas
    gravatar: be209241ca741792b3071d0dd5c55771
    email: bapat.shreyas@gmail.com
    web: https://shreyasb.com
    twitter: https://twitter.com/astroshreyas
    description: "Ex-Coordinator, STAC and Core Developer, EinsteinPy. Worked in Siemens as an Intern. Maintainer at poliastro and pytorch-lightning. Deep Learning Newbie! "
  shishir:
    name: Shishir
    display_name: Shishir (B16144)
    email: b16144@students.iitmandi.ac.in
    description: "Core Team Member 2018"
  anant:
    name: Anant Mishra
    display_name: mishranant
    email: anant.mishra.student@gmail.com
    description: "A CS Undergraduate, intern at Arista Networks"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
